INSERT INTO SONG (ARTIST, NAME) VALUES ('Michael Jackson', 'Billie Jean');
INSERT INTO SONG (ARTIST, NAME) VALUES ('The Beatles', 'Hey Jude');
INSERT INTO SONG (ARTIST, NAME) VALUES ('Queen', 'Bohemian Rhapsody');
INSERT INTO SONG (ARTIST, NAME) VALUES ('Adele', 'Someone Like You');
INSERT INTO SONG (ARTIST, NAME) VALUES ('Elton John', 'Your Song');
INSERT INTO SONG (ARTIST, NAME) VALUES ('Whitney Houston', 'I Will Always Love You');
INSERT INTO SONG (ARTIST, NAME) VALUES ('Bob Dylan', 'Like a Rolling Stone');
INSERT INTO SONG (ARTIST, NAME) VALUES ('Nirvana', 'Smells Like Teen Spirit');
INSERT INTO SONG (ARTIST, NAME) VALUES ('Eagles', 'Hotel California');
INSERT INTO SONG (ARTIST, NAME) VALUES ('Madonna', 'Like a Prayer');
INSERT INTO SONG (ARTIST, NAME) VALUES ('Marvin Gaye', 'What’s Going On');
INSERT INTO SONG (ARTIST, NAME) VALUES ('Prince', 'Purple Rain');
INSERT INTO SONG (ARTIST, NAME) VALUES ('Whitney Houston', 'I Wanna Dance with Somebody');
INSERT INTO SONG (ARTIST, NAME) VALUES ('Led Zeppelin', 'Stairway to Heaven');
INSERT INTO SONG (ARTIST, NAME) VALUES ('Simon & Garfunkel', 'Bridge Over Troubled Water');
INSERT INTO SONG (ARTIST, NAME) VALUES ('Pink Floyd', 'Comfortably Numb');
INSERT INTO SONG (ARTIST, NAME) VALUES ('The Rolling Stones', 'Paint It Black');
INSERT INTO SONG (ARTIST, NAME) VALUES ('U2', 'With or Without You');
INSERT INTO SONG (ARTIST, NAME) VALUES ('Coldplay', 'Yellow');
INSERT INTO SONG (ARTIST, NAME) VALUES ('Bruce Springsteen', 'Born to Run');
INSERT INTO SONG (ARTIST, NAME) VALUES ('The Police', 'Every Breath You Take');
INSERT INTO SONG (ARTIST, NAME) VALUES ('Guns N’ Roses', 'Sweet Child O’ Mine');
INSERT INTO SONG (ARTIST, NAME) VALUES ('Bob Marley & The Wailers', 'One Love');
INSERT INTO SONG (ARTIST, NAME) VALUES ('Rihanna', 'Umbrella');
INSERT INTO SONG (ARTIST, NAME) VALUES ('Taylor Swift', 'Shake It Off');
INSERT INTO SONG (ARTIST, NAME) VALUES ('Alicia Keys', 'If I Ain’t Got You');
INSERT INTO SONG (ARTIST, NAME) VALUES ('Mariah Carey', 'All I Want for Christmas Is You');
INSERT INTO SONG (ARTIST, NAME) VALUES ('Elvis Presley', 'Can’t Help Falling in Love');
INSERT INTO SONG (ARTIST, NAME) VALUES ('Bruno Mars', 'Just the Way You Are');
INSERT INTO SONG (ARTIST, NAME) VALUES ('Billie Eilish', 'Bad Guy');
INSERT INTO SONG (ARTIST, NAME) VALUES ('Kanye West', 'Stronger');
INSERT INTO SONG (ARTIST, NAME) VALUES ('Beyoncé', 'Halo');
INSERT INTO SONG (ARTIST, NAME) VALUES ('Ed Sheeran', 'Shape of You');
INSERT INTO SONG (ARTIST, NAME) VALUES ('Justin Bieber', 'Sorry');
INSERT INTO SONG (ARTIST, NAME) VALUES ('Lady Gaga', 'Bad Romance');
INSERT INTO SONG (ARTIST, NAME) VALUES ('Imagine Dragons', 'Radioactive');
INSERT INTO SONG (ARTIST, NAME) VALUES ('Linkin Park', 'In the End');
INSERT INTO SONG (ARTIST, NAME) VALUES ('Ariana Grande', 'Thank U, Next');
INSERT INTO SONG (ARTIST, NAME) VALUES ('Kendrick Lamar', 'HUMBLE.');
INSERT INTO SONG (ARTIST, NAME) VALUES ('The Weeknd', 'Blinding Lights');
INSERT INTO SONG (ARTIST, NAME) VALUES ('Post Malone', 'Circles');
INSERT INTO SONG (ARTIST, NAME) VALUES ('Sia', 'Chandelier');
INSERT INTO SONG (ARTIST, NAME) VALUES ('Dua Lipa', 'Don’t Start Now');
INSERT INTO SONG (ARTIST, NAME) VALUES ('Shawn Mendes', 'Stitches');
INSERT INTO SONG (ARTIST, NAME) VALUES ('Miley Cyrus', 'Wrecking Ball');
INSERT INTO SONG (ARTIST, NAME) VALUES ('Sam Smith', 'Stay With Me');
INSERT INTO SONG (ARTIST, NAME) VALUES ('John Legend', 'All of Me');
INSERT INTO SONG (ARTIST, NAME) VALUES ('OneRepublic', 'Counting Stars');
INSERT INTO SONG (ARTIST, NAME) VALUES ('Adele', 'Hello');
INSERT INTO SONG (ARTIST, NAME) VALUES ('Maroon 5', 'Sugar');
INSERT INTO SONG (ARTIST, NAME) VALUES ('Coldplay', 'Fix You');
INSERT INTO SONG (ARTIST, NAME) VALUES ('Fleetwood Mac', 'Go Your Own Way');
INSERT INTO SONG (ARTIST, NAME) VALUES ('The Killers', 'Mr. Brightside');
INSERT INTO SONG (ARTIST, NAME) VALUES ('Radiohead', 'Creep');
INSERT INTO SONG (ARTIST, NAME) VALUES ('Outkast', 'Hey Ya!');
INSERT INTO SONG (ARTIST, NAME) VALUES ('Queen & David Bowie', 'Under Pressure');
INSERT INTO SONG (ARTIST, NAME) VALUES ('Journey', 'Don’t Stop Believin’');
INSERT INTO SONG (ARTIST, NAME) VALUES ('A-ha', 'Take On Me');
INSERT INTO SONG (ARTIST, NAME) VALUES ('Nelly', 'Hot in Herre');
INSERT INTO SONG (ARTIST, NAME) VALUES ('Eminem', 'Lose Yourself');
INSERT INTO SONG (ARTIST, NAME) VALUES ('Jay-Z', 'Empire State of Mind');
INSERT INTO SONG (ARTIST, NAME) VALUES ('Lil Nas X', 'Old Town Road');
INSERT INTO SONG (ARTIST, NAME) VALUES ('Katy Perry', 'Firework');
INSERT INTO SONG (ARTIST, NAME) VALUES ('Taylor Swift', 'Blank Space');
INSERT INTO SONG (ARTIST, NAME) VALUES ('Skrillex', 'Bangarang');
INSERT INTO SONG (ARTIST, NAME) VALUES ('Avicii', 'Wake Me Up');
INSERT INTO SONG (ARTIST, NAME) VALUES ('Coldplay', 'Viva La Vida');
INSERT INTO SONG (ARTIST, NAME) VALUES ('Snoop Dogg', 'Drop It Like It’s Hot');
INSERT INTO SONG (ARTIST, NAME) VALUES ('Drake', 'One Dance');
INSERT INTO SONG (ARTIST, NAME) VALUES ('Billie Eilish', 'when the party’s over');
INSERT INTO SONG (ARTIST, NAME) VALUES ('Post Malone', 'Sunflower');
INSERT INTO SONG (ARTIST, NAME) VALUES ('Lorde', 'Royals');
INSERT INTO SONG (ARTIST, NAME) VALUES ('Khalid', 'Talk');
INSERT INTO SONG (ARTIST, NAME) VALUES ('Bruno Mars', 'Uptown Funk');
INSERT INTO SONG (ARTIST, NAME) VALUES ('Ed Sheeran', 'Thinking Out Loud');
INSERT INTO SONG (ARTIST, NAME) VALUES ('Sam Smith', 'Too Good at Goodbyes');
INSERT INTO SONG (ARTIST, NAME) VALUES ('Justin Timberlake', 'Cry Me a River');
INSERT INTO SONG (ARTIST, NAME) VALUES ('Adele', 'Rolling in the Deep');
INSERT INTO SONG (ARTIST, NAME) VALUES ('Florence + The Machine', 'Dog Days Are Over');
INSERT INTO SONG (ARTIST, NAME) VALUES ('The Weeknd', 'Save Your Tears');
INSERT INTO SONG (ARTIST, NAME) VALUES ('Rihanna', 'Diamonds');
INSERT INTO SONG (ARTIST, NAME) VALUES ('Sia', 'Cheap Thrills');
INSERT INTO SONG (ARTIST, NAME) VALUES ('Bruno Mars', 'Just The Way You Are');
INSERT INTO SONG (ARTIST, NAME) VALUES ('Kelly Clarkson', 'Since U Been Gone');
INSERT INTO SONG (ARTIST, NAME) VALUES ('Britney Spears', 'Toxic');
INSERT INTO SONG (ARTIST, NAME) VALUES ('Shakira', 'Hips Don’t Lie');
INSERT INTO SONG (ARTIST, NAME) VALUES ('Luis Fonsi & Daddy Yankee', 'Despacito');
INSERT INTO SONG (ARTIST, NAME) VALUES ('Bon Jovi', 'Livin’ on a Prayer');
INSERT INTO SONG (ARTIST, NAME) VALUES ('Green Day', 'Boulevard of Broken Dreams');
INSERT INTO SONG (ARTIST, NAME) VALUES ('Muse', 'Uprising');
INSERT INTO SONG (ARTIST, NAME) VALUES ('Red Hot Chili Peppers', 'Californication');
INSERT INTO SONG (ARTIST, NAME) VALUES ('Led Zeppelin', 'Whole Lotta Love');
INSERT INTO SONG (ARTIST, NAME) VALUES ('Creedence Clearwater Revival', 'Have You Ever Seen the Rain');
INSERT INTO SONG (ARTIST, NAME) VALUES ('Johnny Cash', 'Ring of Fire');
INSERT INTO SONG (ARTIST, NAME) VALUES ('The Doors', 'Light My Fire');
INSERT INTO SONG (ARTIST, NAME) VALUES ('Simon & Garfunkel', 'The Sound of Silence');
INSERT INTO SONG (ARTIST, NAME) VALUES ('Eric Clapton', 'Tears in Heaven');
INSERT INTO SONG (ARTIST, NAME) VALUES ('Aretha Franklin', 'Respect');
INSERT INTO SONG (ARTIST, NAME) VALUES ('Marvin Gaye', 'Let’s Get It On');
INSERT INTO SONG (ARTIST, NAME) VALUES ('Frank Sinatra', 'My Way');
INSERT INTO SONG (ARTIST, NAME) VALUES ('Ray Charles', 'Georgia on My Mind');
INSERT INTO SONG (ARTIST, NAME) VALUES ('Nina Simone', 'Feeling Good');
INSERT INTO SONG (ARTIST, NAME) VALUES ('Miles Davis', 'So What');
INSERT INTO SONG (ARTIST, NAME) VALUES ('Ella Fitzgerald', 'Summertime');
INSERT INTO SONG (ARTIST, NAME) VALUES ('Johnny Mathis', 'Chances Are');
